name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.4.3
      with:
        version: '340.0.0'
        project_id: capstone-project-c23-pc635
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Deploy to App Engine
      run: gcloud app deploy --quiet
